<a href="https://colab.research.google.com/github/bl00p1ng/Curso-algebra-lineal-python/blob/main/05_Dimension_escalar_vector_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 5. Dimensión de un escalar, vector, matriz o tensor

In [1]:
import numpy as np

`shape` permite saber las dimenciones de un objeto (matriz, vector, tensor). 

**ℹ Nota:** los escalares no tienen dimensión, al usar `shape()` sobre un escalar se obtiene un error.

- El primer número obtenido representa la cantidad de capas de matrices que tiene el tensor.
- El segundo número obtenido representa la cantidad de filas que tiene cada matriz del tensor.
- El tercer número obtenido representa la cantidad de columnas que tiene cada matriz del tensor.

In [3]:
scalar = 5.679
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2], [3, 4]])
tensor = np.array([
    [[1, 2, 3], [4, 5, 6], [6, 7, 8]],
    [[11, 12, 13], [14, 15, 16], [17, 18, 29]],
    [[21, 22, 23], [24, 25, 26], [27, 28, 29]]
])

In [6]:
print(vector, '\nDimensiones:', vector.shape)

[1 2 3] 
Dimensiones: (3,)


In [7]:
print(matrix, '\nDimensiones:', matrix.shape)

[[1 2]
 [3 4]] 
Dimensiones: (2, 2)


`size` retorna el producto de las dimensiones o en otras palabras, el total de elementos.

In [8]:
matrix.size

4

In [10]:
print(tensor, '\nDimensiones:', tensor.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 6  7  8]]

 [[11 12 13]
  [14 15 16]
  [17 18 29]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]] 
Dimensiones: (3, 3, 3)


`shape` en el tensor anterior indica que este tiene 3 matrices de 3 filas y 3 columnas.