<a href="https://colab.research.google.com/github/bl00p1ng/Curso-algebra-lineal-python/blob/main/06_Transposicion_suma_matrices_escalares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 6. Transposición, suma de matrices y escalares

In [1]:
import numpy as np

In [6]:
scalar = 5.679
vector = np.array([3,4,5,6])
matrix = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30], [4,5,6,31], [7,8,9,32]],
    [[11,12,13,33], [14,15,16,34], [17,18,19,35]],
    [[21,22,23,36], [24,25,26,37], [27,28,29,38]]
])

print('Escalar:', scalar, '\n')
print('Vector:\n', vector, '\n')
print('Matriz:\n', matrix, '\n')
print('Tensor:\n', tensor)

Escalar: 5.679 

Vector:
 [3 4 5 6] 

Matriz:
 [[1 2]
 [3 4]
 [5 6]] 

Tensor:
 [[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [27 28 29 38]]]


La transpuesta en Numpy se obtienen con `T`.

**ℹ Nota:** los escalares no tienen transpuesta.

## Transposición en Vectores

En los vectores no hay diferencia entre entre el vector original y la transpuesta a no ser que se efectuen operaciones.

In [5]:
vector_t = vector.T
vector_t

array([3, 4, 5, 6])

## Transposición en Matrices

In [7]:
matrix_t = matrix.T
print(matrix_t, matrix_t.shape)

[[1 3 5]
 [2 4 6]] (2, 3)


## Transposición de Tensores

In [8]:
tensor_t = tensor.T
print(tensor_t, tensor_t.shape)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]] (4, 3, 3)


## Obtener la Matriz original a partir de una transpuesta

$$(A^t)^t=A$$

In [9]:
matrix_t_t = matrix_t.T
matrix_t_t

array([[1, 2],
       [3, 4],
       [5, 6]])

## Suma de Matrices

In [13]:
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[6,5], [4,3], [2,1]])

C = A + B

print(A, '\n')
print(B, '\n')
print(C, '\n')

[[1 2]
 [3 4]
 [5 6]] 

[[6 5]
 [4 3]
 [2 1]] 

[[7 7]
 [7 7]
 [7 7]] 



## Sumarle un escalar a una Matriz

Se le suma el escalar a cada elemento de la matriz.

In [14]:
D = matrix + scalar
D

array([[ 6.679,  7.679],
       [ 8.679,  9.679],
       [10.679, 11.679]])