<a href="https://colab.research.google.com/github/bl00p1ng/Curso-algebra-lineal-python/blob/main/09_Producto_matriz_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 9. Producto interno entre una matriz y un vector

In [1]:
import numpy as np

In [2]:
scalar = 5.679
vector = np.array([2, 3])
matrix = np.array([[1,2], [3,4], [5,6]])

## Producto de una Matriz por un Vector

In [3]:
A = matrix * vector
A

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])

# Producto Interno

In [4]:
B = matrix.dot(vector)
B

array([ 8, 18, 28])

Otra forma de calcular el producto interno:

In [5]:
C = np.dot(matrix, vector)
C

array([ 8, 18, 28])