<a href="https://colab.research.google.com/github/bl00p1ng/Curso-algebra-lineal-python/blob/main/10_Propiedades_producto_interno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 10. Propiedades de las matrices: la multiplicación de matrices es asociativa y distributiva, no es conmutativa

In [ ]:
import numpy as np

In [ ]:
A = np.array([[2,3], [5,7], [11,13]])
B = np.array([[1,3], [2,1]])
C = np.array([[3,1], [4,2]])

## Propiedad Asociativa

In [ ]:
A.dot(B.dot(C))

array([[ 60,  26],
       [145,  63],
       [295, 129]])

In [ ]:
A.dot(B).dot(C)

array([[ 60,  26],
       [145,  63],
       [295, 129]])

## Propiedad distributiva

In [ ]:
A.dot(B + C)

array([[ 26,  17],
       [ 62,  41],
       [122,  83]])

In [ ]:
A.dot(B) + A.dot(C)

array([[ 26,  17],
       [ 62,  41],
       [122,  83]])

## Propiedad conmutativa

In [ ]:
B.dot(C)

array([[15,  7],
       [10,  4]])

In [ ]:
C.dot(B)

array([[ 5, 10],
       [ 8, 14]])

La multiplicación de vectores **SI** es conmutativa:

In [ ]:
v1 = np.array([[2], [7]])
v2 = np.array([[3], [5]])

Se transpone el vector para hacer coincidir las dimensiones y hacer posible la multiplicación

In [ ]:
v1.T.dot(v2)

array([[41]])

In [ ]:
v2.T.dot(v1)

array([[41]])