<a href="https://colab.research.google.com/github/bl00p1ng/Curso-algebra-lineal-python/blob/main/11_Transposicion_producto_de_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 11. Transposición de un producto de matrices

In [1]:
import numpy as np

In [4]:
A = np.array([[2,3], [5,7], [11,13]])
B = np.array([[1,3], [2,1]])

print(A, '\n')
print(B)

[[ 2  3]
 [ 5  7]
 [11 13]] 

[[1 3]
 [2 1]]


In [5]:
A.dot(B).T

array([[ 8, 19, 37],
       [ 9, 22, 46]])

In [6]:
B.T.dot(A.T)

array([[ 8, 19, 37],
       [ 9, 22, 46]])