<a href="https://colab.research.google.com/github/bl00p1ng/Curso-algebra-lineal-python/blob/main/13_Matrices_identidad_inversa_singular.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 13. Tipos especiales de matrices: Identidad, Inversa, Singulares

In [1]:
import numpy as np

## Identidad

`eye` retorna una matriz con solo unos en la diagonal y ceros en el resto de elementos. Todos los valores de la matriz están definidos con floats.

In [2]:
identity = np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
vector = np.array([[2], [3], [5], [7]])

In [4]:
identity.dot(vector)

array([[2.],
       [3.],
       [5.],
       [7.]])

## Inversa

In [7]:
A = np.array([[1,0,1], [0,1,1], [-1,1,1]])
A

array([[ 1,  0,  1],
       [ 0,  1,  1],
       [-1,  1,  1]])

`np.linalg.inv()` permite obtener la inversa con Numpy

In [8]:
A_inverse = np.linalg.inv(A)
A_inverse

array([[ 0.,  1., -1.],
       [-1.,  2., -1.],
       [ 1., -1.,  1.]])

In [9]:
A.dot(A_inverse)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Singular

In [10]:
singular = np.array([[1,1], [1,1]])
singular

array([[1, 1],
       [1, 1]])

Al intentar obtener la inversa se obtiene un error.

In [11]:
np.linalg.inv(singular)

LinAlgError: ignored