<a href="https://colab.research.google.com/github/bl00p1ng/Curso-algebra-lineal-python/blob/main/14_Inversa_sistema_ecuaciones_lineales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 14. Aplicación de la inversa de una matriz para resolver un sistema de ecuaciones lineales

Se tiene el siguiente sistema de ecuaciones:
$$\begin{bmatrix}
3 & 1 \\
2 & 1
\end{bmatrix}
\begin{bmatrix}
x \\
y
\end{bmatrix}=
\begin{bmatrix}
1 \\
1
\end{bmatrix}$$

## Despejar el sistema de ecuaciones usando Numpy

In [1]:
import numpy as np

Configura a Numpy para que si se tienen números muy cercanos a cero se muestre cero en lugar de un número flotante muy pequeño

In [3]:
np.set_printoptions(suppress=True)

In [4]:
A = np.array([[3,1], [2,1]])
A

array([[3, 1],
       [2, 1]])

In [5]:
b = np.array([[1], [1]])
b

array([[1],
       [1]])

In [6]:
A_inverse = np.linalg.inv(A)
A_inverse

array([[ 1., -1.],
       [-2.,  3.]])

In [7]:
x = A_inverse.dot(b)
x

array([[0.],
       [1.]])

Se comprueba el resultado sustituyendo los valores en la ecuación

$$3(0)+1(1)=1 \\
2(0)+1(1)= 1$$

In [8]:
A.dot(x)

array([[1.],
       [1.]])

Se puede usar la misma matriz inversa en una ecuación igualada a otros coeficientes:

$$3x+7=3 \\
2x+y=7$$

In [10]:
sol_2 = A_inverse.dot(np.array([[3], [7]]))
sol_2

array([[-4.],
       [15.]])

Comprobar la solución:

In [12]:
A.dot(sol_2)

array([[3.],
       [7.]])