<a href="https://colab.research.google.com/github/bl00p1ng/Curso-algebra-lineal-python/blob/main/24_Matriz_diagonal_y_simetrica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 24. La matriz diagonal y la matriz simétrica: sus propiedades

In [1]:
import numpy as np

## Matriz Diagonal

`np.diag()` Crea una matriz diagonal.

In [2]:
vector = np.array([1,2,3,4,5])
matrix = np.diag(vector)

matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

Una Matriz Diagonal no tiene  que ser necesariamente cuadrada

In [3]:
matrix[0:4,0:3]

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3],
       [0, 0, 0]])

In [4]:
matrix[0:3,0:4]

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

### Multiplicar una Matriz Diagonal por un vector

In [9]:
A = np.diag([2,3,4,5])
A

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [11]:
v1 = np.array([[1,1,1,1]])
v1

array([[1, 1, 1, 1]])

In [12]:
A.dot(v1.T)

array([[2],
       [3],
       [4],
       [5]])

### Matriz inversa de una Matriz Diagonal

Calcular la inversa manualmente:

In [13]:
A_inv = np.diag([1/2, 1/3, 1/4, 1/5])
A_inv

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.2       ]])

Calcular la inversa con Numpy:

In [16]:
A_inv_cal = np.linalg.inv(A)
A_inv_cal

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.2       ]])

In [17]:
A.dot(A_inv)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Matriz Simétrica

In [18]:
A.T

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [19]:
A

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [20]:
symmetrical = np.array([[1,2,3],
                        [2,-1,7],
                        [3,7,11]])

symmetrical

array([[ 1,  2,  3],
       [ 2, -1,  7],
       [ 3,  7, 11]])

In [21]:
symmetrical.T

array([[ 1,  2,  3],
       [ 2, -1,  7],
       [ 3,  7, 11]])