<a href="https://colab.research.google.com/github/bl00p1ng/Curso-algebra-lineal-python/blob/main/26_Matrices_ortogonales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 26. Matrices ortogonales y sus propiedades

In [1]:
import numpy as np

In [2]:
matrix = np.array([[1,0,0],
                   [0,1,0],
                   [0,0,1]])

matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

$v_1$ ortogonal a $v_2$:

In [3]:
matrix[:,0].dot(matrix[:,1])

0

$v_2$ ortogonal a $v_3$

In [4]:
matrix[:,1].dot(matrix[:,2])

0

$v_1$ es ortogonal a $v_3$

In [5]:
matrix[:,1].dot(matrix[:,2])

0

Revisar que la norma sea 1:

In [6]:
print(np.linalg.norm(matrix[:,0]))
print(np.linalg.norm(matrix[:,1]))
print(np.linalg.norm(matrix[:,2]))

1.0
1.0
1.0


## Revisar que las filas sean ortonormales

In [7]:
print(matrix[0,:].dot(matrix[1,:]))
print(matrix[0,:].dot(matrix[2,:]))
print(matrix[1,:].dot(matrix[2,:]))

0
0
0


Revisar que la norma sea 1:

In [8]:
print(np.linalg.norm(matrix[0,:]))
print(np.linalg.norm(matrix[1,:]))
print(np.linalg.norm(matrix[2,:]))

1.0
1.0
1.0


## Propiedades de las matrices ortogonales

In [9]:
A = np.array([[np.cos(100), -np.sin(100)],
             [np.sin(100), np.cos(100)]])

A

array([[ 0.86231887,  0.50636564],
       [-0.50636564,  0.86231887]])

Comprobar que la matriz sea ortogonal:

In [10]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [15]:
M = A[0,:].dot(A[1,:])
N = A[:,0].dot(A[:,1])

print(round(M,2))    # Es igual a 0.0
print(round(N,2))    # Es igual a 0.0

0.0
-0.0


In [20]:
A_t = A.T

print(A_t.dot(A))
print(A.dot(A_t))

[[ 1. -0.]
 [-0.  1.]]
[[1. 0.]
 [0. 1.]]


In [22]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.86231887, -0.50636564],
       [ 0.50636564,  0.86231887]])

In [23]:
print(A_t)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [24]:
1/A_t.dot(A)

array([[ 1.00000000e+00, -1.25980837e+17],
       [-1.25980837e+17,  1.00000000e+00]])